### ISSUE TITLE
THANK YOU!

### ISSUE THREAD

**Issue by yamanote1138** [ccraig/lsredis#1]
I just wanted to send a quick note to say thank you for putting this together.  I implemented this last night on one of my LemonStand installs, added cache parameters to a few partials and everything just worked. I got everything up and running on production shortly thereafter.

Have you considered contacting Aleksey to see if he'd consider including this as part of the core?  It seems that Redis is just as popular as memcache or apc these days..

Either way, just wanted to say thanks for your hard work! I've forked your repo and if I can find any way to contribute, I'll be sure to do so!

**Comment by ccraig** [comment]
That's great news Chad! Really glad someone else has found it useful! As far as I can tell the main changes that would occur would be updating the predis library when it receives updates. I've been following it and so far not much has changed. Mostly just stuff to do with clustering and the extra commands that a lemonstand caching module wouldn't use. FYI, I removed just about everything that wasn't required to make predis work, from the included predis' repo so it wouldn't take up so much room. Also, if you ever need lemonstand help a bunch of us hang out in the IRC channel ( #lemonstand ).

-charles
